// <auto-generated />
using System;
using ButceAnaliz.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ButceAnaliz.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211203180224_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ButceAnaliz.Models.Dashboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GelenToplamTutar")
                        .HasColumnType("int");

                    b.Property<int>("GidenToplamTutar")
                        .HasColumnType("int");

                    b.Property<int?>("KullanıcıId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullanıcıId");

                    b.ToTable("Dashboards");
                });

            modelBuilder.Entity("ButceAnaliz.Models.Gelir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KullanıcıId")
                        .HasColumnType("int");

                    b.Property<int>("Maas")
                        .HasColumnType("int");

                    b.Property<int>("YatırımKar")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullanıcıId");

                    b.ToTable("Gelir");
                });

            modelBuilder.Entity("ButceAnaliz.Models.Gider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DoğalgazFatura")
                        .HasColumnType("int");

                    b.Property<int>("ElektirikFatura")
                        .HasColumnType("int");

                    b.Property<int>("InternetFatura")
                        .HasColumnType("int");

                    b.Property<int>("KrediTutar")
                        .HasColumnType("int");

                    b.Property<int?>("KullanıcıId")
                        .HasColumnType("int");

                    b.Property<int>("SuFatura")
                        .HasColumnType("int");

                    b.Property<int>("TelefonFatura")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullanıcıId");

                    b.ToTable("Gider");
                });

            modelBuilder.Entity("ButceAnaliz.Models.Kullanıcı", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullanıcıAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullanıcıSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parola")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanıcı");
                });

            modelBuilder.Entity("ButceAnaliz.Models.Yatırım", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("YatırımTürü")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Yatırım");
                });

            modelBuilder.Entity("ButceAnaliz.Models.Dashboard", b =>
                {
                    b.HasOne("ButceAnaliz.Models.Kullanıcı", "Kullanıcı")
                        .WithMany()
                        .HasForeignKey("KullanıcıId");

                    b.Navigation("Kullanıcı");
                });

            modelBuilder.Entity("ButceAnaliz.Models.Gelir", b =>
                {
                    b.HasOne("ButceAnaliz.Models.Kullanıcı", "Kullanıcı")
                        .WithMany()
                        .HasForeignKey("KullanıcıId");

                    b.Navigation("Kullanıcı");
                });

            modelBuilder.Entity("ButceAnaliz.Models.Gider", b =>
                {
                    b.HasOne("ButceAnaliz.Models.Kullanıcı", "Kullanıcı")
                        .WithMany()
                        .HasForeignKey("KullanıcıId");

                    b.Navigation("Kullanıcı");
                });
#pragma warning restore 612, 618
        }
    }
}
